require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/trucks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Truck. As you add validations to Truck, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Truck.create! valid_attributes
      get trucks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      truck = Truck.create! valid_attributes
      get truck_url(truck)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_truck_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      truck = Truck.create! valid_attributes
      get edit_truck_url(truck)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Truck" do
        expect {
          post trucks_url, params: { truck: valid_attributes }
        }.to change(Truck, :count).by(1)
      end

      it "redirects to the created truck" do
        post trucks_url, params: { truck: valid_attributes }
        expect(response).to redirect_to(truck_url(Truck.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Truck" do
        expect {
          post trucks_url, params: { truck: invalid_attributes }
        }.to change(Truck, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post trucks_url, params: { truck: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested truck" do
        truck = Truck.create! valid_attributes
        patch truck_url(truck), params: { truck: new_attributes }
        truck.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the truck" do
        truck = Truck.create! valid_attributes
        patch truck_url(truck), params: { truck: new_attributes }
        truck.reload
        expect(response).to redirect_to(truck_url(truck))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        truck = Truck.create! valid_attributes
        patch truck_url(truck), params: { truck: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested truck" do
      truck = Truck.create! valid_attributes
      expect {
        delete truck_url(truck)
      }.to change(Truck, :count).by(-1)
    end

    it "redirects to the trucks list" do
      truck = Truck.create! valid_attributes
      delete truck_url(truck)
      expect(response).to redirect_to(trucks_url)
    end
  end
end
